
stages:
  - deploy

deploy:
  stage: deploy
  script:
    - git pull origin master
    - pip install -r requirements.txt
    - python manage.py migrate
    - python manage.py collectstatic --noinput
    - sudo service nginx restart